### ISSUE TITLE
Unix socket forwarding issue on Windows platform

### ISSUE THREAD

**Issue by arixmkii** [containers/gvisor-tap-vsock#371]
One can't setup forwarding of Unix socket, because of path being treated as relative. Example command to test

Example command:
```
gvproxy.exe -debug -mtu 1500 -ssh-port 50402 -listen-qemu unix://C:/Users/Arthu/AppData/Local/Temp/podman/podman-machine-default-gvproxy.sock -forward-sock unix://C:/Users/Arthu/AppData/Local/Temp/podman/podman-machine-default-api.sock -forward-dest /run/user/1000/podman/podman.sock -forward-user core -forward-identity C:\\Users\\Arthu\\.local\\share\\containers\\podman\\machine\\machine -pid-file C:\\Users\\Arthu\\AppData\\Local\\Temp\\podman\\gvproxy.pid
```

Output:
```
time="2024-07-19T15:30:54+03:00" level=info msg="gvproxy version git6dbbe08"
time="2024-07-19T15:30:54+03:00" level=info msg="waiting for clients..."
time="2024-07-19T15:30:54+03:00" level=error msg="gvproxy exiting: Error listening on socket: /Users/Arthu/AppData/Local/Temp/podman/podman-machine-default-api.sock: listen unix Users/Arthu/AppData/Local/Temp/podman/podman-machine-default-api.sock: bind: A socket operation encountered a dead network."
time="2024-07-19T15:30:54+03:00" level=error msg="remove C:\\\\Users\\\\Arthu\\\\AppData\\\\Local\\\\Temp\\\\podman\\\\gvproxy.pid: The process cannot access the file because it is being used by another process."
```

Note "Users/Arthu/AppData/Local/Temp/podman/podman-machine-default-api.sock: bind: A socket operation encountered a dead network." part, which is a relative path at this moment.

Offending code is https://github.com/containers/gvisor-tap-vsock/blob/main/pkg/sshclient/ssh_forwarder.go#L115

Quickfix would be to remove this code, this will still work only for boot drive as drive letter is removed, but at least allow it to function for this scenario.

**Comment by cfergeau** [comment]
An URI is `scheme://host/path` (`scheme` followed by `:`, followed by 2 slashes, followed by the hostname, followed by one slash, followed by the path). In `unix://C:/Users`, `C:` is put in `Uri.Host`, and `/Users` in `Uri.Path`.

Since you are referring to a local path, the usual URI for this is `unix:///C:/Users`, ie `unix` followed by `:` followed by 3 slashes, which is an uri with an empty host name, followed by an absolute path. When parsed as an URI, `Uri.Path` contains `/C:/Users`, which I think is the reason for the `TrimPrefix("/")`.
See https://go.dev/play/p/DR3uaOcVQnv for code showing this, and https://github.com/golang/go/issues/6027 for a very old golang issue about this behaviour.

I think your test case will work with `-listen-qemu unix:///C:/Users/Arthu/AppData/Local/Temp/podman/podman-machine-default-gvproxy.sock`

**Comment by arixmkii** [comment]
Thank you for this explanation and examples! It was of a great help!

I did some additional testing. It works this way for `-forward-sock` 

```
gvproxy.exe -debug -mtu 1500 -ssh-port 50402 -listen-qemu unix://C:/Users/Arthu/AppData/Local/Temp/podman/podman-machine-default-gvproxy.sock -forward-sock unix:///C:/Users/Arthu/AppData/Local/Temp/podman/podman-machine-default-api.sock -forward-dest /run/user/1000/podman/podman.sock -forward-user core -forward-identity C:\\Users\\Arthu\\.local\\share\\containers\\podman\\machine\\machine -pid-file C:\\Users\\Arthu\\AppData\\Local\\Temp\\podman\\gvproxy.pid
```

But will not work actually for `-listen-qemu`, because there is no OS specific handling in place (fixable)

```
gvproxy.exe -debug -mtu 1500 -ssh-port 50402 -listen-qemu unix:///C:/Users/Arthu/AppData/Local/Temp/podman/podman-machine-default-gvproxy.sock -forward-sock unix://C:/Users/Arthu/AppData/Local/Temp/podman/podman-machine-default-api.sock -forward-dest /run/user/1000/podman/podman.sock -forward-user core -forward-identity C:\\Users\\Arthu\\.local\\share\\containers\\podman\\machine\\machine -pid-file C:\\Users\\Arthu\\AppData\\Local\\Temp\\podman\\gvproxy.pid
````

Right now I'm thinking should the logic also check if the drive letter and `:` is in place in addition to platform check. It complicates the logic, so, probably treat it as user error and only support absolute paths is ok.
